import csv
import os
import glob

# ==============================
# TERMINAL COLOR CODES
# ==============================
class Colors:
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    CYAN = '\033[96m'
    WHITE = '\033[97m'
    RESET = '\033[0m'

def get_color_for_score(score):
    if score < 40: return Colors.GREEN
    if score < 75: return Colors.YELLOW
    return Colors.RED

def get_grade(avg_stress):
    if avg_stress < 15: return f"{Colors.GREEN}A+ (Perfect, Professional Driving){Colors.RESET}"
    if avg_stress < 25: return f"{Colors.GREEN}A (Smooth & Safe){Colors.RESET}"
    if avg_stress < 35: return f"{Colors.YELLOW}B (Average, Some Aggression){Colors.RESET}"
    if avg_stress < 50: return f"{Colors.RED}C (Aggressive, High Wear){Colors.RESET}"
    return f"{Colors.RED}F (Destructive, Imminent Component Failure){Colors.RESET}"

# ==============================
# MAIN ANALYSIS LOGIC
# ==============================
def analyze_latest_session():
    # 1. Find the most recent CSV file generated by your simulator
    list_of_files = glob.glob('obd_telemetry_log_*.csv')
    if not list_of_files:
        print(f"{Colors.RED}No OBD telemetry data found in this folder! Run the simulator first.{Colors.RESET}")
        return
    
    latest_file = max(list_of_files, key=os.path.getctime)
    print(f"\n{Colors.CYAN}==================================================")
    print(f"        HUMS POST-DRIVE TELEMETRY ANALYSIS        ")
    print(f"=================================================={Colors.RESET}")
    print(f"Reading Dataset: {latest_file}\n")

    # 2. Setup counters for the 4 stress metrics + total
    metrics = {
        "Engine_Stress_pct": {"sum": 0, "max": 0, "abuse_ticks": 0},
        "Drivetrain_Stress_pct": {"sum": 0, "max": 0, "abuse_ticks": 0},
        "Clutch_Stress_pct": {"sum": 0, "max": 0, "abuse_ticks": 0},
        "Driver_Aggression_pct": {"sum": 0, "max": 0, "abuse_ticks": 0},
        "Total_Vehicle_Stress_pct": {"sum": 0, "max": 0, "abuse_ticks": 0}
    }

    row_count = 0
    duration = 0.0
    distance_m = 0.0

    # 3. Read the data
    with open(latest_file, mode='r') as file:
        reader = csv.DictReader(file)
        for row in reader:
            row_count += 1
            duration = float(row["Time_s"])
            speed_kmh = float(row["Speed_kmh"])
            
            # Rough distance calculation (Speed in m/s * DT of 0.03s)
            distance_m += (speed_kmh / 3.6) * 0.03

            # Process each stress category
            for key in metrics.keys():
                val = int(row[key])
                metrics[key]["sum"] += val
                if val > metrics[key]["max"]:
                    metrics[key]["max"] = val
                
                # If stress is over 75%, we count it as "Abuse/Red Zone"
                if val >= 75:
                    metrics[key]["abuse_ticks"] += 1

    if row_count == 0:
        print("Dataset is empty.")
        return

    # 4. Calculate Averages & Percentages
    print(f"{Colors.WHITE}SESSION OVERVIEW:{Colors.RESET}")
    print(f"Duration:      {duration:.1f} seconds")
    print(f"Data Points:   {row_count} frames analyzed")
    print(f"Distance Est:  {distance_m/1000:.2f} km\n")

    print(f"{Colors.WHITE}SUBSYSTEM STRESS BREAKDOWN:{Colors.RESET}")
    print("-" * 50)

    display_names = {
        "Engine_Stress_pct": "1. Engine Load & RPM Stress",
        "Drivetrain_Stress_pct": "2. Drivetrain Torque Stress",
        "Clutch_Stress_pct": "3. Clutch Slip/Heat Stress",
        "Driver_Aggression_pct": "4. Driver Aggression (Jerk)",
    }

    # 5. Print Subsystem Reports
    for key, name in display_names.items():
        avg = metrics[key]["sum"] / row_count
        peak = metrics[key]["max"]
        abuse_time_sec = metrics[key]["abuse_ticks"] * 0.03 # 0.03 is your simulator DT

        avg_color = get_color_for_score(avg)
        peak_color = get_color_for_score(peak)

        print(f"{name}:")
        print(f"   Average Load: {avg_color}{avg:.1f}%{Colors.RESET}")
        print(f"   Peak Spike:   {peak_color}{peak}%{Colors.RESET}")
        if abuse_time_sec > 0:
            print(f"   Time in Danger Zone (>75%): {Colors.RED}{abuse_time_sec:.1f} seconds{Colors.RESET}")
        else:
            print(f"   Time in Danger Zone (>75%): {Colors.GREEN}0.0 seconds{Colors.RESET}")
        print("-" * 50)

    # 6. Final Driver Scoring
    overall_avg = metrics["Total_Vehicle_Stress_pct"]["sum"] / row_count
    overall_peak = metrics["Total_Vehicle_Stress_pct"]["max"]
    
    print(f"\n{Colors.CYAN}==================================================")
    print(f"              FINAL DRIVER EVALUATION             ")
    print(f"=================================================={Colors.RESET}")
    print(f"Overall Average Vehicle Stress: {get_color_for_score(overall_avg)}{overall_avg:.1f}%{Colors.RESET}")
    print(f"Maximum Stress Peak Hit:        {get_color_for_score(overall_peak)}{overall_peak}%{Colors.RESET}")
    print(f"Final Driver Grade:             {get_grade(overall_avg)}\n")


if __name__ == "__main__":
    # This enables ANSI colors in Windows CMD/PowerShell
    os.system('color') 
    analyze_latest_session()